[workspace]
members = ["proxy", "cache-indexer"]
resolver = "2"

[workspace.dependencies]
pingora = "0.6"
pingora-core = "0.6"
pingora-proxy = "0.6"
pingora-cache = "0.6"
tokio = { version = "1", features = ["full"] }
rdkafka = { version = "0.38", features = ["cmake-build"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
opensearch = "2.3"
tracing = "0.1"
tracing-subscriber = "0.3"
async-trait = "0.1"
bytes = "1.0"
sha2 = "0.10"
hex = "0.4"
rcgen = "0.13"
pem = "3.0"
time = "0.3"
